sudo: required
dist: trusty
language: node_js

node_js:
  - '10.9.0'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
      - google-chrome-beta

git:
  depth: 1

cache:
  npm: true
  directories:
    - ./node_modules/

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

env:
  - TASK=test
  - TASK=lint
  - TASK=build
  - TASK=site:build

script:
  - npm run $TASK
  - |
    if [ "$TASK" = "test" ]; then
      cat ./coverage/lcov.info | ./node_modules/.bin/codecov
    fi
